all:
  hosts:
    node1:
      ansible_host: 192.168.222.12
      ip: 192.168.222.12
      access_ip: 192.168.222.12
    node2:
      ansible_host: 192.168.222.133
      ip: 192.168.222.133
      access_ip: 192.168.222.133
    node3:
      ansible_host: 192.168.222.85
      ip: 192.168.222.85
      access_ip: 192.168.222.85
  children:
    kube_control_plane:
      hosts:
        node1:        
    kube_node:
      hosts:        
        node2:
        node3:
    etcd:
      hosts:
        node1:        
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
