all:
  hosts:
    node1:
      ansible_host: 192.168.0.19
      ip: 192.168.0.19
      access_ip: 192.168.0.19
    node2:
      ansible_host: 192.168.0.22
      ip: 192.168.0.22
      access_ip: 192.168.0.22
    node3:
      ansible_host: 192.168.0.23
      ip: 192.168.0.23
      access_ip: 192.168.0.23
  children:
    kube_control_plane:
      hosts:
        node1:        
    kube_node:
      hosts:        
        node2:
        node3:
    etcd:
      hosts:
        node1:        
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
