all:
  hosts:
    node1:
      ansible_host: 192.168.0.10
      ip: 192.168.0.10
      access_ip: 192.168.0.10
    node2:
      ansible_host: 192.168.0.6
      ip: 192.168.0.6
      access_ip: 192.168.0.6
    node3:
      ansible_host: 192.168.0.8
      ip: 192.168.0.8
      access_ip: 192.168.0.8
  children:
    kube_control_plane:
      hosts:
        node1:        
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:        
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
